# Настройка базовых сообщений
messages:
  no-permission: '&x&f&b&f&1&0&0&l▶ &fУ вас недостаточно прав для этого.'
  reloaded: '&x&f&b&f&1&0&0&l▶ &fПлагин перезагружен.'
  only-players: '&x&f&b&f&1&0&0&l▶ &fКоманда только для игроков.'
  player-not-found: '&x&f&b&f&1&0&0&l▶ &fИгрок не найден.'