name: IncAPI
version: ${project.version}
main: ru.incrementstudio.incapi.Main
api-version: 1.13
authors: [IncrementStudio++]
description: API для всех плагинов | vk.com/incrementstudio
website: vk.com/incrementstudio
